# Generated by Django 5.2.7 on 2025-12-08 16:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cor',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cor',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cores_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cor',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cor',
            name='excluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cor',
            name='excluido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cores_excluidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
