# Generated by Django 5.2.7 on 2025-12-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0002_cor_criado_em_cor_criado_por_cor_excluido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cor',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
