# Generated by Django 5.2.7 on 2025-12-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0003_cor_ordem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminventario',
            name='observacao',
        ),
    ]
