# Generated by Django 5.2.7 on 2025-12-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0004_remove_iteminventario_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminventario',
            name='quantidade_pe_direito',
            field=models.IntegerField(default=0, verbose_name='Quantidade Pé Direito'),
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='quantidade_pe_esquerdo',
            field=models.IntegerField(default=0, verbose_name='Quantidade Pé Esquerdo'),
        ),
    ]
