# Generated by Django 5.2.7 on 2025-12-12 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0005_iteminventario_quantidade_pe_direito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminventario',
            name='quantidade',
        ),
    ]
