# Generated by Django 5.2.7 on 2025-12-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0006_remove_iteminventario_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo',
            field=models.CharField(choices=[('operador', 'Operador'), ('qualidade', 'Qualidade'), ('loja', 'Loja')], default='operador', max_length=20),
        ),
    ]
