# Generated by Django 5.2.7 on 2025-12-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0007_alter_perfilusuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichainventario',
            name='setor',
            field=models.CharField(default='Injetora', max_length=50),
        ),
    ]
