# Generated by Django 5.2.7 on 2025-12-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0008_alter_fichainventario_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichainventario',
            name='setor',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
