# Generated by Django 5.2.7 on 2025-12-17 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_itemrequisicao_tamanho'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tamanho',
        ),
    ]
